export const COUNTER = {
    CREATE: "CREATE_COUNTER",
    EDIT: "EDIT_COUNTER",
    REMOVE: "REMOVE_COUNTER",
};

export const TARIFF = {
    CREATE: "CREATE_TARIFF",
    REMOVE: "REMOVE_TARIFF",
};

export const TARIFF_DATA = {
    CREATE: "CREATE_DATA",
    REMOVE: "REMOVE_DATA",
};

export const COUNTERS_VALUES = {
    UPDATE: "UPDATE_COUNTERS_VALUES",
};
