export const COUNTER = {
    CREATE: "CREATE_COUNTER",
    EDIT: "EDIT_COUNTER",
    REMOVE: "REMOVE_COUNTER",
};

export const TARIFF = {
    CREATE: "CREATE_TARIFF",
    UPDATE: "UPDATE_TARIFF",
    REMOVE: "REMOVE_TARIFF",
};

export const TARIFF_DATA = {
    CREATE: "CREATE_DATA",
    UPDATE: "UPDATE_DATA",
    EDIT: "EDIT_DATA",
    RESET_EDIT: "RESET_EDIT_DATA",
    REMOVE: "REMOVE_DATA",
    REMOVE_ALL_TARIFFS_DATA: "REMOVE_ALL_TARIFFS_DATA",
};

export const COUNTERS_VALUES = {
    UPDATE: "UPDATE_COUNTERS_VALUES",
    OPEN: "OPEN_COUNTERS_VALUES",
};
